#!/system/bin/sh
#

insmod /system/lib/modules/cpufreq_ondemand.ko

echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

echo 80 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo 15 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
echo 30 > /sys/devices/system/cpu/cpufreq/ondemand/down_differential

